

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;

/**
 * This class represents a single transaction that the user has inputted.
 */
public class Transaction {

  /** The amount of money exchanged in this transaction. */
  private double amount;
  /** The category this transaction falls under. */
  private String category;
  /** The time at which this transaction took place */
  private String timestamp;

  /**
   * Create a transaction with given details (timestamp is autogenerated)
   * @param amount The amount of money exchanged in this transaction
   * @param category The category this transaction falls under
   */
  public Transaction(double amount, String category) {
    this.amount = amount;
    this.category = category;
    this.timestamp = generateTimestamp();
  }

  /**
   * Return amount of money in transaction
   * @return get the amount of money that was exchanged in this transaction
   */
  public double getAmount() {
    return amount;
  }
  /**
   * Set amount of money in transaction
   * @param amount set the amount of money in this transaction
   */
  public void setAmount(double amount) {
    this.amount = amount;
  }
  /**
   * Return category of transaction
   * @return get the category of this transaction
   */
  public String getCategory() {
    return category;
  }
  /**
   * Set category of transaction
   * @param category set the category of this transaction
   */
  public void setCategory(String category) {
    this.category = category; 
  }
  /**
   * Get timpstamp of transaction
   * @return get the time of this transaction
   */
  public String getTimestamp() {
    return timestamp;
  }
  /**
   * Create timestamp and convert to string
   * @return returns the current timestamp as a string
   */
  private String generateTimestamp() {
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy HH:mm");  
    return sdf.format(new Date());
  }

}